# Generated by Django 4.2.5 on 2023-10-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_date_order_date_order_order_date_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
